/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp3heritage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jacques
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    ArrayList<Agent> mesAgents;
    
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAgents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Marié", "Salaire", "Impôt"
            }
        ));
        tblAgents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)tblAgents.getModel();

            mesAgents = new ArrayList<>();
        
            Agent ag1 = new Agent(1,"Enzo", true, 20000);
            Agent ag2 = new Agent(2,"Noa", false, 20000);
            Agent ag3 = new Agent(3,"Lilou", false, 150000);
            Agent ag4 = new Agent(4,"Milo", true, 175000);

            AgentAvecEnfant aae1 = new AgentAvecEnfant(5,"Bastien", true, 230000, 4);
            AgentAvecEnfant aae2 = new AgentAvecEnfant(6,"Elise", false, 125000, 2);
            AgentAvecEnfant aae3 = new AgentAvecEnfant(7,"Alexandra", true, 280000, 1);
            AgentAvecEnfant aae4 = new AgentAvecEnfant(8,"Olivier", false, 160000, 3);

            mesAgents.add(ag1);
            mesAgents.add(ag2);
            mesAgents.add(ag3);
            mesAgents.add(ag4);
            mesAgents.add(aae1);
            mesAgents.add(aae2);
            mesAgents.add(aae3);
            mesAgents.add(aae4);

            Collections.sort(mesAgents);
            Vector agents = null;
            
            for (Agent ag : mesAgents)
            {
                agents = new Vector();
                agents.add(ag.numAgent);
                agents.add(ag.nomAgent);
                agents.add(ag.marie);
                agents.add(ag.salaire);
                agents.add(ag.calculerImpot());
                dtm.addRow(agents);
            }
            tblAgents.setModel(dtm);
    }//GEN-LAST:event_formWindowOpened

    private void tblAgentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgentsMouseClicked
        // TODO add your handling code here:
        
        int numAgent = Integer.parseInt(tblAgents.getValueAt(tblAgents.getSelectedRow(), 0).toString());
        JOptionPane.showMessageDialog(this, mesAgents.get(numAgent-1).afficherInfo());
        
        
    }//GEN-LAST:event_tblAgentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgents;
    // End of variables declaration//GEN-END:variables
}
